// src/app/gamemode-ui/gamemode-ui.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-gamemode-ui',
  templateUrl: './gamemode-ui.component.html',
  styleUrls: ['./gamemode-ui.component.scss']
})
export class GamemodeUiComponent implements OnInit {

  @Input() public left: number[] = [];
  @Input() public right: number[] = [];
  @Input() public coloring: { n: number, color: string }[] = [];
  @Input() public timeLeft = 60;
  @Input() public click: (left: boolean, idx: number) => void = () => {};

  constructor() { }

  ngOnInit(): void {
  }

  color(n: number): string {
    for (const color of this.coloring) {
      if (color.n === -1 || color.n !== n) { continue; }
      return color.color;
    }
    return 'white';
  }

}

<div id='header'>
    <p id='time-left'>Time left: {{this.timeLeft / 1000 | number: '1.0-0'}}s</p>
</div>
<div id='game-main'>
    <div id='left' class='container'>
        <h1
            *ngFor="let n of left; let idx=index"
            [style.color]="color(n)"
            (click)="this.click(true, idx)"
            class="number"
        >{{n}}</h1>
    </div>
    <div id='right' class='container'>
        <h1
            *ngFor="let n of right; let idx=index"
            [style.color]="color(n)"
            (click)="this.click(false, idx)"
            class="number"
        >{{n}}</h1>
    </div>
</div>

// src/static/gamemodes/GamemodeUi.tsx
import * as React from 'react';
import './GamemodeUi.scss';

interface Props {
    left: number[],
    right: number[],
    coloring: { n: number, color: string }[],
    timeLeft: number,
    click: (left: boolean, idx: number) => void
}

type State = Record<string, never>;

export default class GamemodeUiComponent extends React.Component<Props, State> {

    render() {
        return (
            <>
                <div id='header'>
                    <p id='time-left'>Time left: {Math.round(this.props.timeLeft / 1000)}s</p>
                </div>
                <div id='game-main'>
                    <div id='left' className='container'>
                        {
                            this.props.left.map((n, idx) => {
                                let color = 'white';
                                this.props.coloring.forEach((coloring) => {
                                    if(coloring.n === -1 || coloring.n !== n) return;
                                    color = coloring.color;
                                });
                                return (
                                    <h1 className='number' key={idx} style={{color}} onClick={ () => this.props.click(true, idx) }>{n}</h1>
                                );
                            })
                        }
                    </div>
                    <div id='right' className='container'>
                        {
                            this.props.right.map((n, idx) => {
                                let color = 'white';
                                this.props.coloring.forEach((coloring) => {
                                    if(coloring.n === -1 || coloring.n !== n) return;
                                    color = coloring.color;
                                });
                                return (
                                    <h1 className='number' key={idx} style={{color}} onClick={ () => this.props.click(false, idx) }>{n}</h1>
                                );
                            })
                        }
                    </div>
                </div>
            </>
        );
    }

}
