// src/static/gamemodes/keepAlive/KeepAlive.tsx
import * as React from 'react';
import './KeepAlive.scss';
import { logEvent } from 'firebase/analytics';
import { getNewListsAndNumber } from '../../../common/utils/MainUtils';
import { CommonState, defaultCommonState } from '../../../common/utils/StateUtils';
import { analytics } from '../..';
import { Link } from 'react-router-dom';
import GamemodeUiComponent from '../GamemodeUi';

interface State extends CommonState {
    finished: boolean,
    timeLeft: number,
    timeAddition: number
}

type Props = Record<string, never>;

export default class KeepAlive extends React.Component<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            ...defaultCommonState('keepAlive'),
            finished: true,
            timeLeft: 60,
            timeAddition: 0
        };
    }

    resetGame() {
        this.setState(getNewListsAndNumber());
    }

    async fullReset() {
        this.resetGame();
        this.setState({
            start: Date.now(),
            time: 0,
            newRecord: false,
            finished: false,
            timeLeft: 60,
            timeAddition: 0
        });
    }

    finishGame() {
        const time = Date.now() - this.state.start;
        this.setState({
            finished: true,
            time: time,
            bestTime: time > this.state.bestTime ? time : this.state.bestTime,
            newRecord: time > this.state.bestTime
        }, () => {
            window.localStorage.setItem('keepAlive.best', this.state.bestTime.toString());
            logEvent(analytics, 'keep_alive_finished');
        });
    }

    click(left: boolean, idx: number) {
        const won = (left ? this.state.left : this.state.right)[idx] == this.state.number;
        this.setState({
            timeAddition: this.state.timeAddition + (won ? 10 : -10)
        }, () => this.resetGame());
    }

    componentDidMount() {
        setInterval(() => {
            if(!this.state.finished) this.setState({
                timeLeft: ((this.state.start + 60 * 1000) - Date.now()) + this.state.timeAddition * 1000
            }, () => {
                if(!this.state.finished && this.state.timeLeft <= 0) setTimeout(this.finishGame.bind(this));
            });
        }, 10);
    }

    render(): React.ReactNode {
        return (
            <div id='keep-alive'>
                {
                    !this.state.finished ? (
                        <>
                            <GamemodeUiComponent
                                left={this.state.left}
                                right={this.state.right}
                                timeLeft={this.state.timeLeft}
                                click={this.click.bind(this)}
                                coloring={[ ]}
                            />
                        </>
                    ) : (
                        <div id='end'>
                            <h1 id='time'>
                                {this.state.newRecord ? 'New Best Time ' : ''}{this.state.time / 1000}s
                            </h1>
                            <div id='buttons'>
                                <button onClick={() => this.fullReset()} id='new-game' className='button'>New game</button>
                                <Link to='/' id='Home' className='button'>Home</Link>
                            </div>
                        </div>
                    )
                }
            </div>
        );
    }

}

// src/app/keep-alive/keep-alive.component.ts
import { Component, OnInit } from '@angular/core';
import { AngularFireAnalytics } from '@angular/fire/analytics';
import { Gamemode } from '../utils/GamemodeUtils';

enum GameState {
  PLAYING,
  FINISHED
}

@Component({
  selector: 'app-keep-alive',
  templateUrl: './keep-alive.component.html',
  styleUrls: ['./keep-alive.component.scss']
})
export class KeepAliveComponent extends Gamemode implements OnInit {

  public GameState = GameState;

  public state = GameState.FINISHED;
  public flashing: string | null = null;
  public timeLeft = 60;
  public timeAddition = 0;

  constructor(private analytics: AngularFireAnalytics) {
    super('keepAlive');
  }

  startGame(): void {
    super.reset();
    this.state = GameState.PLAYING;
    this.timeLeft = 60;
    this.timeAddition = 0;
  }

  endGame(): void {
    const time = Date.now() - this.start;

    this.state = GameState.FINISHED;
    this.time = time;
    this.bestTime = time > this.bestTime ? time : this.bestTime;
    this.newRecord = time > this.bestTime;

    window.localStorage.setItem('keepAlive.best', this.bestTime.toString());
    this.analytics.logEvent('keep_alive_finished');
  }

  click(left: boolean, idx: number): void {
    const won = (left ? this.left : this.right)[idx] === this.pickedNumber;
    this.timeAddition += won ? 10 : -10;
    this.flashing = won ? '#145c14' : '#5c1414';
    this.newListsAndNumber();

    setTimeout(() => {
      this.flashing = null;
    }, 250);
  }

  ngOnInit(): void {
    setInterval(() => {
      if (this.state === GameState.FINISHED) { return; }
      this.timeLeft = ((this.start + 60 * 1000) - Date.now()) + this.timeAddition * 1000;
      if (this.timeLeft <= 0) { this.endGame(); }
    }, 10);
  }

}



<app-gamemode-ui *ngIf="this.state === GameState.PLAYING else end"
    [left]="this.left"
    [right]="this.right"
    [timeLeft]="this.timeLeft"
    [click]="this.click.bind(this)"
    [coloring]="[ ]"
    [style.backgroundColor]="this.flashing ? this.flashing : ''"
></app-gamemode-ui>

<ng-template #end>
    <div id='end'>
        <h1 id='time'>
            {{this.newRecord ? 'New Best Time ' : ''}}{{this.time / 1000}}s
        </h1>
        <div id='buttons'>
            <button (click)="this.startGame()" id='new-game' class='button'>New game</button>
            <a [routerLink]="[ '/' ]" id='home' class='button'>Home</a>
        </div>
    </div>
</ng-template>
